name: release workkflow demo

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
    
    - name: Build the project
      run: npm run build

    - name: Zip build artifacts
      run: zip -r dist.zip ./dist

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: dist.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifact

    - name: Extract Release Notes
      id: extract_notes
      run: |
        VERSION=${GITHUB_REF##*/}
        echo "Version: $VERSION"
        RELEASE_NOTES=$(awk "/## \\[$VERSION\\]/,/## \\[/ { if (!/## \\[/) print }" CHANGELOG.md)
        echo "release_notes<<EOF" >> $GITHUB_ENV
        echo "$RELEASE_NOTES" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist.zip
        token:  ${{ secrets.NEW_CI_CD }}
        release_name: Release ${{ github.ref }} 
        body: |
          ## 变更日志
          ${{ env.release_notes }}
      env:
        GITHUB_TOKEN: ${{ secrets.NEW_CI_CD }}
