name: release workkflow demo

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
    
    - name: Build the project
      run: npm run build

    - name: Zip build artifacts
      run: zip -r dist.zip ./dist

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: dist.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifact

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist.zip
      env:
        GITHUB_TOKEN: ${{ secrets.NEW_CI_CD }}
